[package]
name = "isucondition-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5.10", features = ["mysql", "time", "runtime-tokio-native-tls"] }
chrono = "0.4.19"
serde_json = "1.0.78"
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.53"
async-trait = "0.1.52"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.30"
