name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: mysql://isucon:isucon@localhost:3306/isucondition_test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          docker-compose up -d
          MYSQL_DBNAME=isucondition_test ./sql/init.sh
          cargo build --verbose
    - name: Run tests
      run: |
          docker-compose up -d
          MYSQL_DBNAME=isucondition_test ./sql/init.sh
          cargo test --verbose
