name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: mysql://isucon:isucon@localhost:3306/isucondition_test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start services
      run: |
          docker-compose up -d

          # wait for db ready
          while ! mysql -h 127.0.0.1 -P 3306 -e "SELECT 1" >/dev/null 2>&1
          do
            sleep 1
          done

          docker-compose exec -T db mysql -e "create database isucondition_test"
          MYSQL_DBNAME=isucondition_test ./sql/init.sh
    - name: Build
      run: |
          cargo build --verbose
    - name: Run tests
      run: |
          cargo test --workspace --verbose -- --test-threads=1 --nocapture
